module Handler.AufgabeVorlagen where

import Import

getAufgabeVorlagenR :: ServerUrl -> AufgabeTyp -> Handler Html
getAufgabeVorlagenR server aufgabeTyp = do
  let vorlagen = ["ctnfa", "alextest", "NFA: ab", "DFA_vollst: ab", "NFA: =<3b", "NFA: |w|>3", "NFA: 3 teilt |w|_a", "NFA-ohne-aba", "NFA-mod3/2", "NFA: mod", "NFA: wx", "NFA:wx2", "NFA: |w|_a=|w|_b mod 3", "EXP2MinNFA", "EXP2MinNFAhelp", "Aufgabe 1.1", "Aufgabe 1.2.a", "Aufgabe 1.2.b", "Aufgabe 2.1.a", "Aufgabe 2.3.a", "Aufgabe 2.3.b", "Aufgabe 2.6", "Aufgabe 2.1.c", "Aufgabe 2.1.b", "NFA ohne ba*b", "Aufgabe 3.3.b", "Aufgabe 3.5", "Aufgabe 4.2.a", "Aufgabe 4.2.b", "Aufgabe 4.5", "Aufgabe 4.6", "2", "NFA:demo", "NFA:ab+ba", "NFA: ohne bab", "NFA: |w|_a=|w|_b mod 3", "NFA: wx", "NFA: =<3b", "NFA:ab...nichtdet", "NFA: ab...det", "RA2MinDFA", "NFA: wx2", "FA-nicht3", "NFA-Ostern", "DFA-Ostern", "NFA-u0g1", "NFA-aibjckdla7", "NFA-Xa7X", "NFA-suffixababcd", "DFA-suffixababcd", "DFA-csuffixababcd", "NFAtoDFA1", "NFA-prefixbc-infixaca", "DFA-prefixbc-infixaca", "NFAa++", "DFA-Suffix-bb", "Minimal-DFA-1", "EA_Anzahl_ab", "NFA-Xa4Xb4", "DEA_Auto_matte", "EA_Auto_matte", "NFA-a4bicjdka4", "NFA-suffixbcbcdab", "DFA-suffixbcbcdab", "NFA-praefixabc-infixabd", "DFA-praefixabc-infixabd", "NFA-nicht3", "NFA1", "NFA2", "NFA3", "NFA-Bin3", "NFA4", "NFA5", "minDEA_Ende10", "MinimDEA1", "MinimDEA2", "NFA1", "DFA1", "DFA2", "NFA6", "MinimDEA3", "DFA-Mini1", "DFA-Mini2", "DFA4", "RE -> NFA", "GR -> NFA", "NFA-Rechtslinear", "NFA-Ostern", "DFA-Ostern", "EA_Anzahl_ab", "NFA-Infix-ab", "NFA: |w|>3", "NFA-HS: wx", "NFA-HS:ohne-Infix", "NFA:Postfix", "NFA:auto", "NFA-DFA2", "DFA-ostern", "DFA-HS1", "HA3.3", "HA3.6b", "HA3.6e", "NFA-suffixbcbcdab", "NFA-nicht3", "Potenzmengenk", "HA5.3.a", "HA5.3.b", "A01 DFA ohne bab", "A02 DFA ab+ba", "RLG->NFA", "RE->NFA", "HA6.3a", "HA6.6a", "A05 wxy minimieren", "A05z wxy als NEA", "A06 eNEA -> NEA", "A07 Produktautomat", "A18 regG -> minDEA-118", "A00a DFA w01 ", "A00b NFA awc", "A01 DFA ohne bab", "A02 NFA ubv2c0c", "A04 wxy minimieren", "A04z wxy als NEA", "A05 eNEA -> NEA", "A06 Produktautomat", "EA_Praefix_Infix", "EA_auto_matte", "Potenzmengenk", "NFA1", "DFA1", "DFA2", "NFA3", "NFA4", "NFA5", "NFA6", "DFA6", "MinAut_Aufg.3.4b", "DFA10", "Typ3-GR->NFA (korrigiert)", "Typ3-Gr->NFA2", "Convert_To_NFA-Direct-142", "ttt", "NFA: ab", "less_than_4_b", "NFA: <4b", "DFA: endet_auf_bb", "NFA: rest=2", "NFA: wx", "NFA:ab", "student_enten", "NFA-Demo", "NFA1", "NFA2", "NFA-HS1", "DFA-ostern", "NFA4", "NFA-HS2", "NFA5", "Eps-NFA1", "EA_Auto_matte", "DEA_Auto_matte", "Ostern", "Potenzmengenk", "NFA-Demo", "NFA1", "NFA2", "NFA2a", "NFA2b", "DFA1", "DFA6.1.a", "NFA6.4", "DFA6.4", "MDFA7.4", "NFA3", "DFA2", "regAusdruck->EA", "GR->NFA", "NFA-Demo", "NFA1", "NFA2", "NFA3", "16.1-DFA-B", "NFA5  (statt DFA4)", "DFA1 (korrigiert)", "EA_auto_matte", "NFA-Ostern", "DFA-Ostern"] :: [Text]
  defaultLayout $ do
    $(widgetFile "aufgabeVorlagen")
