AlleResultate: Alle Resultate
Abmelden: Abmelden
Anmelden: Anmelden
Anzeigen: Anzeigen
Aufgabe: Aufgabe
AufgabeAnlegen: Aufgabe anlegen
AufgabeAufgabe: Aufgabenstellung
AufgabeBearbeiten: Aufgabe bearbeiten
AufgabeBearbeitungszeit: Bearbeitungszeit
AufgabeBeginnDatum: Bearbeitungsbeginn der Aufgabe (Datum)
AufgabeBeginnZeit: Bearbeitungsbeginn der Aufgabe (Uhrzeit)
AufgabeBewertung: Bewertung
AufgabeBewertungVorher: Vorherige Bewertung
AufgabeEingeben: Eingeben
AufgabeEinstellen: Aufgabe einstellen
AufgabeEinstellungen: Einstellungen
AufgabeEndeDatum: Bearbeitungsende der Aufgabe (Datum)
AufgabeEndeZeit: Bearbeitungsende der Aufgabe (Uhrzeit)
AufgabeGesamtwertung: Gesamtwertung
AufgabeHighscore: Highscore
AufgabeHinweis: Hinweis
AufgabeHochladen: Hochladen
AufgabeKonfiguration: Konfiguration
AufgabeKonfigurieren: Aufgabe konfigurieren
AufgabeKonfigurationTyp: Typ der Konfiguration
AufgabeXLösen aufgabe@Text: Aufgabe #{aufgabe} lösen
AufgabeLösungEinsenden: Lösung einsenden
AufgabeLösungTyp: Typ der Lösung
Aufgaben: Aufgaben
AufgabenAktuell: Aktuelle Aufgaben
AufgabenAlle: Alle Aufgaben
AufgabeName: Name
AufgabenErledigt erledigt@Integer ziel@Integer prozent@Integer: Von #{show ziel} #{plural ziel "Pflichtaufgabe" "Pflichtaufgaben"} haben Sie bis jetzt #{show erledigt} erledigt. Das sind #{show prozent} Prozent.
AufgabeStatus: Status
AufgabeXTesten aufgabe@Text: Aufgabe #{aufgabe} testen
AufgabeTesten: Aufgabe testen
AufgabeTyp: Aufgabentyp wählen
AufgabeVorlagen: Aufgabenvorlage wählen
AufgabeVorlageStandard: Standardvorlage / letzte Konfiguration
AufgabeZeitAktuell zeit@UTCTime: noch bis #{formatTime defaultTimeLocale "%d.%m.%Y %H:%M:%S" zeit} Uhr
AufgabeZeitNachher zeit@UTCTime: vorbei seit #{formatTime defaultTimeLocale "%d.%m.%Y %H:%M:%S" zeit} Uhr
AufgabeZeitVorher zeit@UTCTime: erst ab #{formatTime defaultTimeLocale "%d.%m.%Y %H:%M:%S" zeit} Uhr
Ausstehend: Ausstehend
Austragen: Austragen
Bearbeiten: Bearbeiten
Behalten: Behalten
BeispielLaden: Beispiel laden
BewertungAusstehend: Ausstehend
BewertungNein: Nein
BewertungOk wert@Integer: Okay (#{show wert} Punkte)
BewertungOkay punkte@Integer größe@Integer: Okay (P: #{show punkte}, G: #{show größe})
BewertungReset: Zurückgesetzt
CacheLöschen: Cache Löschen
Direktoren: Direktoren
DirektorAbsetzen: Direktor absetzen
DirektorAbgesetzt: Direktor abgesetzt
DirektorErnennen: Direktor ernennen
DirektorErnannt: Direktor ernannt
Einschreiben: Einschreiben
EinschreibungBeginnDatum: Beginn der Einschreibung (Datum)
EinschreibungBeginnZeit: Beginn der Einschreibung (Datum)
EinschreibungDauer beginn@UTCTime ende@UTCTime: Eine Einschreibung ist nur im Zeitraum vom #{formatTime defaultTimeLocale "%d.%m.%Y %H:%M:%S" beginn} Uhr bis #{formatTime defaultTimeLocale "%d.%m.%Y %H:%M:%S" ende} Uhr möglich.
EinschreibungEndeDatum: Ende der Einschreibung (Datum)
EinschreibungEndeZeit: Ende der Einschreibung (Datum)
Email: E-Mail
Gesamtpunktzahl: Total
Größe: Größe
Gruppe: Übungsgruppe
GruppeAnlegen: Übungsgruppe anlegen
GruppeAusgetragen: Übungsgruppe wurde verlassen
GruppeBearbeiten: Übungsgruppe bearbeiten
GruppeEingeschrieben: Erfolgreich in Übungsgruppe eingeschrieben
Gruppen: Übungsgruppen
GruppeName: Gruppenname
GruppenHinweis: Um die Aufgaben für eine Vorlesung bearbeiten zu können, müssen Sie in einer Übungsgruppe dieser Vorlesung eingeschrieben sein.
GruppeNummer: Gruppennummer
GruppeVoll: Einschreibung ist nicht möglich. Die gewählte Übungsgruppe ist voll.
HighscoreAnzeigen: Highscore
HighscoreHoch: Hoch
HighscoreKeine: Keine Highscore
HighscoreNiedrig: Niedrig
Identifikationsnummer: ID
IstEingeschrieben: Sie sind in einer Übungsgruppe eingeschrieben.
KeineAufgaben: Keine passenden Aufgaben gefunden.
KeineAufgabenTypen: Es gibt noch keine Aufgabentypen auf diesem Aufgabenserver.
KeineDirektoren: Es gibt leider keine Direktoren dieser Schule.
KeineEinschreibungen: Sie sind in keine Übungsgruppe dieser Vorlesung eingeschrieben.
KeineSchulen: Es gibt leider keine Schulen, auf die Sie zugreifen können.
KeineSemesters: Für diese Schule wurden noch keine Semester definiert.
KeineStudentenErnennen: Es gibt leider keine Studenten, die ernannt werden können.
KeineTutoren: Es gibt leider keine Tutoren zu dieser Vorlesung.
KeineGruppen: Es gibt leider keien Übungsgruppen zu dieser Vorlesung.
KeineVorlesungen: Es gibt leider keine Vorlesungen in diesem Semester.
Löschen: Löschen
Lösen: Lösen
Lösung: Lösung
LösungAbsenden: Lösung absenden
Matrikelnummer: Matrikelnummer
Name: Name
Nein: Nein
Neins: Nein
NichtAutorisiert: Sie sind für diese Anfrage leider nicht autorisiert. Die Anfrage wurde zurückgewiesen und der Zugriff verweigert.
Okays: Okay
PersönlicheDaten: Persönliche Daten
Plätze: Plätze
Punkte: Punkte
Referent: Referent
Registrieren: Registrieren
ResultatePflicht: Resultate der Pflichtaufgaben
Schule: Schule
SchuleAngelegt: Schule wurde angelegt
SchuleAnlegen: Schule anlegen
SchuleBearbeiten: Schule bearbeiten
SchuleBearbeitet: Schule wurde bearbeitet
Schulen: Schulen
SchuleName: Schulname
SchuleSprache: Bevorzugte Sprache
SchuleSuffix: E-Mail-Suffix
SchuleWählen: Bitte wählen Sie ihre Schule!
Semester: Semester
Semesters: Semester
SemesterAnlegen: Semester anlegen
SemesterBearbeiten: Semester bearbeiten
SemesterBeginnDatum: Semesterbeginn (Datum)
SemesterBeginnZeit: Semesterbeginn (Uhrzeit)
SemesterDauer beginn@UTCTime ende@UTCTime: dauert vom #{formatTime defaultTimeLocale "%d.%m.%Y %H:%M:%S" beginn} Uhr bis #{formatTime defaultTimeLocale "%d.%m.%Y %H:%M:%S" ende} Uhr
SemesterEndeDatum: Semesterende (Datum)
SemesterEndeZeit: Semesterende (Uhrzeit)
SemesterName: Bezeichnung
Server: Server
ServerErstellen: Server erstellen
Servers: Server wählen
ServerWählen: Server wählen
SpracheDE: Deutsch
SpracheNL: Niederländisch
SpracheUK: Britisches Englisch
StatistikAnzeigen: Statistik anzeigen
StatusDemonstration: Demonstration
StatusOptional: Optional
StatusPflicht: Pflicht
Studenten: Studenten
StudentenEingeschrieben: Eingeschriebene Studenten
StudentenMaximal: Maximale Einschreibungen
TagesNachricht: Mitteilung des Tages
Testen: Testen
Tutor: Tutor ernennen
Tutoren: Tutoren
TutorAbsetzen: Tutor absetzen
TutorAbgesetzt: Tutor abgesetzt
TutorErnennen: Tutor ernennen
TutorErnannt: Tutor ernannt
VorherigeEinsendungLaden: Vorherige Einsendung laden
Vorlesung: Vorlesung
VorlesungAnlegen: Vorlesung anlegen
VorlesungBearbeiten: Vorlesung bearbeiten
Vorlesungen: Vorlesungen
VorlesungName: Bezeichnung
Vorname: Vorname
Waisenkinder: Waisenkinder
WaisenkinderBeschreibung: Studenten Ihrer Schule, die keine Übungsgruppe gewählt haben.
ZuAufgaben: Zu den Aufgaben
