AlleResultate: Alle Resultate
Abmelden: Abmelden
Anmelden: Anmelden
Anzeigen: Anzeigen
Aufgabe: Aufgabe
AufgabeAnlegen: Aufgabe anlegen
AufgabeAufgabe: Aufgabenstellung
AufgabeBearbeiten: Aufgabe bearbeiten
AufgabeBearbeitungszeit: Bearbeitungszeit
AufgabeBeginnDatum: Bearbeitungsbeginn der Aufgabe (Datum)
AufgabeBeginnZeit: Bearbeitungsbeginn der Aufgabe (Uhrzeit)
AufgabeBewertung: Bewertung
AufgabeBewertungVorher: Vorherige Bewertung
AufgabeEingeben: Eingeben
AufgabeEinstellen: Aufgabe einstellen
AufgabeEinstellungen: Einstellungen
AufgabeEndeDatum: Bearbeitungsende der Aufgabe (Datum)
AufgabeEndeZeit: Bearbeitungsende der Aufgabe (Uhrzeit)
AufgabeGesamtwertung: Gesamtwertung
AufgabeHighscore: Highscore
AufgabeHinweis: Hinweis
AufgabeHochladen: Hochladen
AufgabeKonfiguration: Konfiguration
AufgabeKonfigurieren: Aufgabe konfigurieren
AufgabeKonfigurationTyp: Typ der Konfiguration
AufgabeXLösen aufgabe@Text: Aufgabe #{aufgabe} lösen
AufgabeLösungEinsenden: Lösung einsenden
AufgabeLösungTyp: Typ der Lösung
Aufgaben: Aufgaben
AufgabenAktuell: Aktuelle Aufgaben
AufgabenAlle: Alle Aufgaben
AufgabeName: Name
AufgabeStatus: Status
AufgabeXTesten aufgabe@Text: Aufgabe #{aufgabe} testen
AufgabeTesten: Aufgabe testen
AufgabeTyp: Aufgabentyp wählen
AufgabeVorlagen: Aufgabenvorlage wählen
AufgabeVorlageStandard: Standardvorlage / letzte Konfiguration
AufgabeZeitVorher zeit@UTCTime: noch bis #{formatTime defaultTimeLocale "%d.%m.%Y %H:%M:%S" zeit} Uhr
AufgabeZeitNachher zeit@UTCTime: vorbei seit #{formatTime defaultTimeLocale "%d.%m.%Y %H:%M:%S" zeit} Uhr
Ausstehend: Ausstehend
Austragen: Austragen
Bearbeiten: Bearbeiten
Behalten: Behalten
BeispielLaden: Beispiel laden
Besuchen: Besuchen
CacheLöschen: Cache Löschen
Direktoren: Direktoren
DirektorAbsetzen: Direktor absetzen
DirektorErnennen: Direktor ernennen
Einschreiben: Einschreiben
EinschreibungBeginnDatum: Beginn der Einschreibung (Datum)
EinschreibungBeginnZeit: Beginn der Einschreibung (Datum)
EinschreibungDauer beginn@UTCTime ende@UTCTime: Eine Einschreibung ist im Zeitraum vom #{formatTime defaultTimeLocale "%d.%m.%Y %H:%M:%S" beginn} Uhr bis #{formatTime defaultTimeLocale "%d.%m.%Y %H:%M:%S" ende} Uhr möglich
EinschreibungEndeDatum: Ende der Einschreibung (Datum)
EinschreibungEndeZeit: Ende der Einschreibung (Datum)
Email: E-Mail
Gesamtpunktzahl: Total
Größe: Größe
Gruppe: Übungsgruppe
GruppeAnlegen: Übungsgruppe anlegen
GruppeBearbeiten: Übungsgruppe bearbeiten
Gruppen: Übungsgruppen
GruppeName: Gruppenname
GruppeNummer: Gruppennummer
HighscoreAnzeigen: Highscore
HighscoreHoch: Hoch
HighscoreKeine: Keine Highscore
HighscoreNiedrig: Niedrig
Identifikationsnummer: ID
KeineAufgaben: Keine passenden Aufgaben gefunden.
KeineAufgabenTypen: Es gibt noch keine Aufgabentypen auf diesem Aufgabenserver.
KeineDirektoren: Es gibt leider keine Direktoren dieser Schule.
KeineStudentenErnennen: Es gibt leider keine Studenten, die ernannt werden können.
KeineTutoren: Es gibt leider keine Tutoren zu dieser Vorlesung.
KeineVorlesungen: Es gibt leider keine Vorlesungen in diesem Semester.
Löschen: Löschen
Lösen: Lösen
Lösung: Lösung
LösungAbsenden: Lösung absenden
Matrikelnummer: Matrikelnummer
Name: Name
Nein: Nein
Neins: Nein
Okays: Okay
PersönlicheDaten: Persönliche Daten
Plätze: Plätze
Punkte: Punkte
Referent: Referent
Registrieren: Registrieren
ResultatePflicht: Resultate der Pflichtaufgaben
Schule: Schule
SchuleAnlegen: Schule anlegen
SchuleBearbeiten: Schule bearbeiten
Schulen: Schulen
SchuleName: Schulname
SchuleSuffix: E-Mail-Suffix
SchuleWählen: Bitte wählen Sie ihre Schule!
Semester: Semester
Semesters: Semester
SemesterAnlegen: Semester anlegen
SemesterBearbeiten: Semester bearbeiten
SemesterBeginnDatum: Semesterbeginn (Datum)
SemesterBeginnZeit: Semesterbeginn (Uhrzeit)
SemesterDauer beginn@UTCTime ende@UTCTime: dauert vom #{formatTime defaultTimeLocale "%d.%m.%Y %H:%M:%S" beginn} Uhr bis #{formatTime defaultTimeLocale "%d.%m.%Y %H:%M:%S" ende} Uhr
SemesterEndeDatum: Semesterende (Datum)
SemesterEndeZeit: Semesterende (Uhrzeit)
SemesterName: Bezeichnung
Server: Server
ServerErstellen: Server erstellen
Servers: Server wählen
ServerWählen: Server wählen
StatistikAnzeigen: Statistik anzeigen
StatusDemonstration: Demonstration
StatusOptional: Optional
StatusPflicht: Pflicht
Studenten: Studenten
StudentenEingeschrieben: Eingeschriebene Studenten
StudentenMaximal: Maximale Einschreibungen
TagesNachricht: Mitteilung des Tages
Testen: Testen
Tutor: Tutor ernennen
Tutoren: Tutoren
TutorAbsetzen: Tutor absetzen
TutorErnennen: Tutor ernennen
VorherigeEinsendungLaden: Vorherige Einsendung laden
Vorlesung: Vorlesung
VorlesungAnlegen: Vorlesung anlegen
VorlesungBearbeiten: Vorlesung bearbeiten
Vorlesungen: Vorlesungen
VorlesungName: Bezeichnung
Vorname: Vorname
Waisenkinder: Waisenkinder
WaisenkinderBeschreibung: Studenten Ihrer Schule, die keine Übungsgruppe gewählt haben.