AlleResultate: Alle Resultate
Anzeigen: Anzeigen
Ausstehend: Ausstehend
Bearbeiten: Bearbeiten
Behalten: Behalten
BeispielLaden: Beispiel laden
Bezeichnung: Bezeichnung
CacheLöschen: Cache Löschen
Gesamtpunktzahl: Total
Größe: Größe
Gruppen: Gruppen
Gruppennummer: Gruppennummer
LösungAbsenden: Lösung absenden
Matrikelnummer: Matrikelnummer
Name: Name
Nein: Nein
Neins: Nein
Okays: Okay
Punkte: Punkte
Referent: Referent
ResultatePflicht: Resultate der Pflichtaufgaben
Schulen: Schulen
SchuleWählen: Bitte wählen Sie ihre Schule!
Studenten: Studenten
VorherigeEinsendungLaden: Vorherige Einsendung laden
Vorname: Vorname
Waisenkinder: Waisenkinder
WaisenkinderBeschreibung: Studenten Ihrer Schule, die keine Übungsgruppe gewählt haben.