TextToMsg text@Text: #{text}

AlleResultate: All Results
Abmelden: Log out
Anmelden: Log in
Anzeigen: View
Aufgabe: Exercise
AufgabeAnlegen: Create exercise
AufgabeAngelegt: Exercise created
AufgabeAufgabe: Task
AufgabeBearbeiten: Edit exercise
AufgabeBearbeitet: Exerise edited
AufgabeBearbeitungszeit: Completion period
AufgabeBeginnDatum: Task available from (date)
AufgabeBeginnZeit: Task available from (time)
AufgabeBenutzerId: Choose an identification number
AufgabeBenutzerIdZufall: Random identification number
AufgabeBewertung: Rating
AufgabeBewertungVorher: Previous rating
AufgabeEingeben: Solve
AufgabeEinsendungGespeichert: Log file entry
AufgabeEinstellen: Configure exercise
AufgabeEinstellungen: Settings
AufgabeEndeDatum: End of completion period (date)
AufgabeEndeZeit: End of completion period (time)
AufgabeEntfernt: Exercise deleted
AufgabeGesamtwertung: Total score
AufgabeHighscore: High score
AufgabeHinweis: Advice
AufgabeHochladen: Upload
AufgabeKonfiguration: Configuration
AufgabeKonfigurationFehler: Configuration has errors
AufgabeKonfigurieren: Configure exercise
AufgabeKonfigurationTyp: Type of the configuration
AufgabeXLösen aufgabe@Text: Solve exercise #{aufgabe}
AufgabeLösungEinsenden: Submit solution
AufgabeLösungTyp: Type of the solution
Aufgaben: Exercises
AufgabenAktuell: Current exercises
AufgabenAlle: All exercises
AufgabeName: Name
AufgabeNameVergeben: This name was used for an other exercise of this kind already.
AufgabenErledigt erledigt@Integer ziel@Integer prozent@Integer: You have solved #{show erledigt} of #{show ziel} #{plural ziel "exercise" "exercises"}, i.e. #{show prozent} percent.
AufgabeSignaturUpdate: Attention! A missing signature was added.
AufgabeStatus: State
AufgabeXTesten aufgabe@Text: Try exercise #{aufgabe}
AufgabeTesten: Try exercise
AufgabeTestenMitId: Try exercise with certain user id
AufgabeTyp: Choose kind of exercise
AufgabeVorbei: The completion period is over, but you can try the exercise, if you want.
AufgabeVorlagen: Choose template for exercise
AufgabeVorlageStandard: Standard template / last configuration
AufgabeZeitAktuell zeit@UTCTime: open until #{formatTime defaultTimeLocale "%d/%m/%Y %H:%M:%S" zeit}
AufgabeZeitNachher zeit@UTCTime: over since #{formatTime defaultTimeLocale "%d/%m/%Y %H:%M:%S" zeit}
AufgabeZeitVorher zeit@UTCTime: starting at #{formatTime defaultTimeLocale "%d/%m/%Y %H:%M:%S" zeit}
Ausstehend: Pending
Austragen: Disenrol
Autotool: Autotool
Bearbeiten: Edit
Behalten: Keep
BeispielLaden: Load example
BewertungAusstehend: Pending
BewertungBearbeiten: Edit rating
BewertungNein: No
BewertungOk wert@Integer: Okay (#{show wert} points)
BewertungOkay punkte@Integer size@Integer: Okay (P: #{show punkte}, S: #{show size})
BewertungReset: Reset
CacheLeeren: Clear cache
CacheGeleert pfad@Text: Cache cleared (#{pfad})
Direktoren: Headmasters
DirektorAbsetzen: Dismiss headmaster
DirektorAbgesetzt: Headmaster dismissed
DirektorErnennen: Appoint headmaster
DirektorErnannt: Headmaster appointed
Einschreiben: Enrol
EinschreibungBeginnDatum: Begin of enrolment period (date)
EinschreibungBeginnZeit: Begin of enrolment period (time)
EinschreibungDauer beginn@UTCTime ende@UTCTime: Enrolment is only possible from #{formatTime defaultTimeLocale "%d/%m/%Y %H:%M:%S" beginn} to #{formatTime defaultTimeLocale "%d/%m/%Y %H:%M:%S" ende}.
EinschreibungEndeDatum: End of enrolement period (Datum)
EinschreibungEndeZeit: End of enrolment period (Uhrzeit)
Einsendung: Last submission
EinsendungAnzeigen: Show last submission
EinsendungBewerten: Rerate
EinsendungBewertung: Rating
EinsendungBewertungAlt: Previous rating
EinsendungBewertungNotwendig: The rating field must not be empty.
EinsendungFalsch: Your submission is no solution for the given task. Please read the given advices!
Email: E-mail
Fehler: An error occured
Gesamtpunktzahl: Total
Größe: Size
Gruppe: Tutorial group
GruppeAnlegen: Create tutorial group
GruppeAngelegt: Tutorial group created
GruppeAusgetragen: Leave tutorial group
GruppeBearbeiten: Edit tutorial group
GruppeBearbeitet: Tutorial group edited
GruppeEingeschrieben: Successfully enroled in tutorial group.
GruppeEntfernen: Do you really want to delete the tutorial group. If so, please confirm by pressing the Button again.
GruppeEntfernt: Tutorial group deleted
Gruppen: Tutorial groups
GruppeName: Group name
GruppenHinweis: In order to solve an exercise of a lecture you have to be enroled.
GruppeNummer: Group number
GruppeVoll: Enrolment not possible. This tutorial group is full.
GruppeZuKlein: Tutorial group too small.
HighscoreAnzeigen: High score
HighscoreHoch: High
HighscoreKeine: No high score
HighscoreNiedrig: Low
Identifikationsnummer: ID
IstEingeschrieben: You are enroled.
KeineAufgaben: There are no appropriate exercises.
KeineAufgabenstellung: No task could be found.
KeineAufgabenTypen: No kinds of exercise could be found on this exercise server.
KeineBewertung: No rating could be found.
KeineDirektoren: There are no headmasters at this school.
KeineEinschreibung: You are not enroled in any tutorial group of this lecture.
KeineEinschreibungen: There are no students enroled in tutorial groups.
KeineEinsendung: There are no submissions yet.
KeineSchulen: You do not have access to any school.
KeineSemesters: There are no semesters for this school.
KeineStudentenErnennen: There are no students who could be appointed. 
KeineTutoren: There are no lecturers for this lecture.
KeineGruppen: There are no tutorial groups for this lecture.
KeineVorlesungen: There are no lectures for this semester.
Löschen: Delete
Lösen: Solve
Lösung: Solution
LösungAbsenden: Submit solution
Matrikelnummer: Student number
Name: Name
Nein: No
Neins: Nos
NeueSprache: You have choosen English as language.
NichtAutorisiert: You are not authorised for this request. The request was rejected and no access granted.
Okay: Okay
Okays: Okay
PersönlicheDaten: Personal data
Plätze: Seats
Punkte: Points
Referent: Lecturer
Registrieren: Register
Reset: Reset
ResultatePflicht: Results of compulsory tasks
Schule: School
SchuleAngelegt: School created
SchuleAnlegen: Create school
SchuleBearbeiten: Edit school
SchuleBearbeitet: School edited
Schulen: Schools
SchuleName: Name of school
SchuleSprache: Preferred language
SchuleSuffix: E-mail suffix
SchuleWählen: Please choose your school!
Semester: Semester
Semesters: Semesters
SemesterAnlegen: Create semester
SemesterAngelegt: Semester created
SemesterBearbeiten: Edit semester
SemesterBearbeitet: Semester edited
SemesterBeginnDatum: Semester begin (date)
SemesterBeginnZeit: Semester begin (time)
SemesterDauer beginn@UTCTime ende@UTCTime: lasts from #{formatTime defaultTimeLocale "%d/%m/%Y %H:%M:%S" beginn} to #{formatTime defaultTimeLocale "%d/%m/%Y %H:%M:%S" ende}
SemesterEndeDatum: Semester end (date)
SemesterEndeZeit: Semester end (time)
SemesterName: Name
Server: Server
ServerErstellen: Create server
Servers: Choose server
ServerWählen: Choose server
SpracheDE: German
SpracheNL: Dutch
SpracheUK: British english
Statistik: Statistics
StatistikAnzeigen: Show statistics
StatusDemonstration: Demonstration
StatusOptional: Optional
StatusPflicht: Compulsory
Studenten: Students
StudentenEingeschrieben: Enroled students
StudentenMaximal: Maximum enrolments
TagesNachricht: Message of the day
Testen: Try
Tutor: Appoint Lecturer
Tutoren: Lecturers
TutorAbsetzen: Dismiss Lecturer
TutorAbgesetzt: Lecturer dismissed
TutorErnennen: Appoint Lecturer
TutorErnannt: Lecturer appointed
VorherigeEinsendungLaden: Load previous submission
Vorlesung: Lecture
VorlesungAnlegen: Create lecture
VorlesungAngelegt: Lecture created
VorlesungBearbeiten: Edit lecture
VorlesungBearbeitet: Lecture edited
Vorlesungen: Lectures
VorlesungEntfernen: Do you want to delete the lecture? If so, please confirm by pressing the button again.
VorlesungEntfernt: Lecture deleted
VorlesungName: Name
Vorname: First name
Waisenkinder: Orphans
WaisenkinderBeschreibung: Students who are not enroled in any tutorial group.
ZuAufgaben: Show exercises
